version: 0.0
os: linux
files:
  - source: RandomNameFromListServer.py 
    destination: /webapps
  - source: index.html
    destination: /webapps
  - source: launch.sh
    destination: /webapps
  - source: shutdown.sh
    destination: /webapps
permissions:
  - object: /webapps
    pattern: "*.py"
    mode: 755
  - object: /webapps
    pattern: "*.sh"
    mode: 777
hooks:
  ApplicationStop:
    - location: /webapps/shutdown.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: /webapps/launch.sh
      timeout: 60
      runas: root
