version: 0.0
os: linux
files:
  - source: RandomNameFromListServer.py 
    destination: /webapps
  - source: index.html
    destination: /webapps
permissions:
  - object: /webapps
    pattern: "*.py"
    mode: 755
hooks:
  ApplicationStop:
    - location: shutdown.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: launch.sh
      timeout: 60
      runas: root
